cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region: "us-east-2"

memories:
  logging:
    tracing-aspect-enabled: true
  temp-folder:
    path: src/main/resources/
    temp-file-prefix: tempFile
  bucket:
    name: projectmemories


spring:
  application:
    name: memories
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
      database: memories
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/memories-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8280